name: SonarQube Analysis
on:
  push:
    branches:
      - master
      - 'release-v*'

jobs:
  sonar:
    name: SonarQube Analysis
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run tests with coverage
        run: |
          npm test -- --coverage || echo "No tests configured yet"
        continue-on-error: true

      - name: Setup SonarQube Scanner
        uses: warchant/setup-sonar-scanner@v7

      - name: SonarQube Scan
        run: |
          sonar-scanner \
            -Dsonar.host.url=https://sonarcloud.io \
            -Dsonar.token=${{ secrets.SONAR_TOKEN }} \
            -Dsonar.branch.name=${{ github.ref_name }} \
            -Dsonar.projectKey=burgan-tech_vnext-cli \
            -Dsonar.organization=burgan-tech \
            -Dsonar.projectName="vNext CLI" \
            -Dsonar.projectVersion=1.0.0 \
            -Dsonar.sources=. \
            -Dsonar.sourceEncoding=UTF-8 \
            -Dsonar.exclusions="**/node_modules/**,**/coverage/**,**/dist/**,**/build/**,**/*.min.js,**/test/**,**/tests/**" \
            -Dsonar.test.exclusions="**/node_modules/**,**/test/**,**/tests/**,**/*.test.js,**/*.spec.js" \
            -Dsonar.javascript.lcov.reportPaths=coverage/lcov.info \
            -Dsonar.testExecutionReportPaths=coverage/test-reporter.xml \
            -Dsonar.coverage.exclusions="**/test/**,**/tests/**,**/*.test.js,**/*.spec.js,**/coverage/**" \
            -Dsonar.cpd.exclusions="**/test/**,**/tests/**"
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

